title: Mallikarjuna T.
url: "https://kvmpk-gita-arjuna.github.io/"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "about"
   link: "/"
 - name: "publications"
   link: "research"
 - name: "projects"
   link: "projects"
 - name: "cv"
   link: "Mallikarjuna_CV.pdf"
 - name: "contact"
   link: "contact"
